# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#2fafff" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#ff5f59", bold = true, italic = true, underline = true }
find_position = { fg = "#b6a0ff", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#44bc44", bg = "#44bc44" }
marker_cut      = { fg = "#fec43f", bg = "#ff5f59" }
marker_marked   = { fg = "#2fafff", bg = "#7dcfff" }
marker_selected = { fg = "#fec43f", bg = "#fec43f" }

# Count
count_copied   = { fg = "#1e1e1e", bg = "#44bc44" }
count_cut      = { fg = "#1e1e1e", bg = "#fec43f" }
count_selected = { fg = "#1e1e1e", bg = "#2fafff" }

# Border
border_symbol = "│"
border_style  = { fg = "#61647a" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#ffffff", bg = "#1e1e1e", bold = true }
inactive = { fg = "#1e1e1e", bg = "#ffffff" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#1e1e1e", bg = "#2fafff", bold = true }
normal_alt  = { fg = "#2fafff", bg = "#1e1e1e" }

# Select mode
select_main = { fg = "#1e1e1e", bg = "#44bc44", bold = true }
select_alt  = { fg = "#2fafff", bg = "#1e1e1e" }

# Unset mode
unset_main = { fg = "#1e1e1e", bg = "#b6a0ff", bold = true }
unset_alt  = { fg = "#2fafff", bg = "#1e1e1e" }

# : }}}


# : Status bar {{{

[status]
overall = { fg = "#2fafff" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }


# Progress
progress_label = { fg = "#1e1e1e", bold = true }
progress_normal = { fg = "#2fafff", bg = "#1e1e1e" }
progress_error = { fg = "#ff5f59", bg = "#1e1e1e" }

# Permissions
perm_sep   = { fg = "#2fafff" }
perm_type  = { fg = "#44bc44" }
perm_read  = { fg = "#fec43f" }
perm_write = { fg = "#ff5f59" }
perm_exec  = { fg = "#b6a0ff" }


# : }}}

# : Pick {{{

[pick]
border = { fg = "#2fafff" }
active = { fg = "#b6a0ff", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#2fafff" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#2fafff" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#2fafff" }
title   = {}
hovered = { fg = "#b6a0ff", underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#1e1e1e" }
cand            = { fg = "#44bc44" }
rest            = { fg = "#a9b1d6" }
desc            = { fg = "#b6a0ff" }
separator       = "  "
separator_style = { fg = "#989898" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#44bc44" }
run     = { fg = "#b6a0ff" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#ffffff", bg = "#1e1e1e" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#44bc44" }
title_warn  = { fg = "#ff5f59" }
title_error = { fg = "#fec43f" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#fec43f" },

	# Media
	{ mime = "video/*", fg = "#ff5f59" },
	{ mime = "audio/*", fg = "#ff5f59" },

	# Archives
	{ mime = "application/zip",             fg = "#b6a0ff" },
	{ mime = "application/x-tar",           fg = "#b6a0ff" },
	{ mime = "application/x-bzip*",         fg = "#b6a0ff" },
	{ mime = "application/x-bzip2",         fg = "#b6a0ff" },
	{ mime = "application/x-7z-compressed", fg = "#b6a0ff" },
	{ mime = "application/x-rar",           fg = "#b6a0ff" },
	{ mime = "application/x-xz",            fg = "#b6a0ff" },

	# Documents
	{ mime = "application/doc",        fg = "#44bc44" },
	{ mime = "application/epub+zip",   fg = "#44bc44" },
	{ mime = "application/pdf",        fg = "#44bc44" },
	{ mime = "application/rtf",        fg = "#44bc44" },
	{ mime = "application/vnd.*",      fg = "#44bc44" },

	# Fallback
	{ url = "*", fg = "#ffffff" },
	{ url = "*/", fg = "#2fafff" },
]

# : }}}
